# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build binary
    cmds:
      - go generate ./...
      - go vet ./...
      - go build -o bin/ae .

  test:
    desc: Run all tests
    cmds:
      - go test ./...
      - nu test/test.nu

  install:
    desc: Install locally
    deps: [build]
    cmds:
      - cp bin/ae ~/bin/ae
