// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package db

import (
	"context"
	"database/sql"
)

const getAttribute = `-- name: GetAttribute :one
SELECT value FROM attribute WHERE attribute = ?
`

func (q *Queries) GetAttribute(ctx context.Context, attribute string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAttribute, attribute)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const setAttribute = `-- name: SetAttribute :exec
INSERT OR REPLACE INTO attribute (attribute, value) VALUES (?, ?)
`

type SetAttributeParams struct {
	Attribute string         `db:"attribute"`
	Value     sql.NullString `db:"value"`
}

func (q *Queries) SetAttribute(ctx context.Context, arg SetAttributeParams) error {
	_, err := q.db.ExecContext(ctx, setAttribute, arg.Attribute, arg.Value)
	return err
}
