// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deps.sql

package db

import (
	"context"
)

const deleteDep = `-- name: DeleteDep :exec
DELETE FROM dep WHERE task_id = ? AND after_id = ?
`

type DeleteDepParams struct {
	TaskID  string `db:"task_id"`
	AfterID string `db:"after_id"`
}

func (q *Queries) DeleteDep(ctx context.Context, arg DeleteDepParams) error {
	_, err := q.db.ExecContext(ctx, deleteDep, arg.TaskID, arg.AfterID)
	return err
}

const deleteDepsByTask = `-- name: DeleteDepsByTask :exec
DELETE FROM dep WHERE task_id = ? OR after_id = ?
`

type DeleteDepsByTaskParams struct {
	TaskID  string `db:"task_id"`
	AfterID string `db:"after_id"`
}

// Cleanup for unsplit: remove all deps where task is involved
func (q *Queries) DeleteDepsByTask(ctx context.Context, arg DeleteDepsByTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteDepsByTask, arg.TaskID, arg.AfterID)
	return err
}

const insertDep = `-- name: InsertDep :exec
INSERT INTO dep (task_id, after_id) VALUES (?, ?)
`

type InsertDepParams struct {
	TaskID  string `db:"task_id"`
	AfterID string `db:"after_id"`
}

func (q *Queries) InsertDep(ctx context.Context, arg InsertDepParams) error {
	_, err := q.db.ExecContext(ctx, insertDep, arg.TaskID, arg.AfterID)
	return err
}

const listDependentsOfTask = `-- name: ListDependentsOfTask :many
SELECT task_id, after_id FROM dep WHERE after_id = ?
`

// Get all tasks that depend on a given task (successors)
func (q *Queries) ListDependentsOfTask(ctx context.Context, afterID string) ([]Dep, error) {
	rows, err := q.db.QueryContext(ctx, listDependentsOfTask, afterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dep{}
	for rows.Next() {
		var i Dep
		if err := rows.Scan(&i.TaskID, &i.AfterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepsForTask = `-- name: ListDepsForTask :many
SELECT task_id, after_id FROM dep WHERE task_id = ?
`

// Get all predecessors of a given task
func (q *Queries) ListDepsForTask(ctx context.Context, taskID string) ([]Dep, error) {
	rows, err := q.db.QueryContext(ctx, listDepsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dep{}
	for rows.Next() {
		var i Dep
		if err := rows.Scan(&i.TaskID, &i.AfterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
