// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Attribute struct {
	Attribute string         `db:"attribute"`
	Value     sql.NullString `db:"value"`
}

type Dep struct {
	TaskID  string `db:"task_id"`
	AfterID string `db:"after_id"`
}

type Record struct {
	ID     int64     `db:"id"`
	Task   string    `db:"task"`
	Ts     time.Time `db:"ts"`
	Source string    `db:"source"`
	Text   string    `db:"text"`
}

type Task struct {
	ID        string         `db:"id"`
	ParentID  sql.NullString `db:"parent_id"`
	Title     sql.NullString `db:"title"`
	Body      sql.NullString `db:"body"`
	Context   sql.NullString `db:"context"`
	Status    sql.NullString `db:"status"`
	Position  sql.NullInt64  `db:"position"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
}
