// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package db

import (
	"context"
)

const countNonSystemRecordsByTask = `-- name: CountNonSystemRecordsByTask :one
SELECT COUNT(*) FROM record WHERE task = ? AND source != 'system'
`

// Count non-system records for a specific task (used for unsplit precondition check)
func (q *Queries) CountNonSystemRecordsByTask(ctx context.Context, task string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNonSystemRecordsByTask, task)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecordsByTask = `-- name: DeleteRecordsByTask :exec
DELETE FROM record WHERE task = ?
`

// For unsplit child cleanup
func (q *Queries) DeleteRecordsByTask(ctx context.Context, task string) error {
	_, err := q.db.ExecContext(ctx, deleteRecordsByTask, task)
	return err
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO record (task, ts, source, text)
VALUES (?, CURRENT_TIMESTAMP, ?, ?)
`

type InsertRecordParams struct {
	Task   string `db:"task"`
	Source string `db:"source"`
	Text   string `db:"text"`
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertRecord, arg.Task, arg.Source, arg.Text)
	return err
}

const listRecordsByPrefix = `-- name: ListRecordsByPrefix :many
SELECT id, task, ts, source, text FROM record
WHERE task = ?1 OR task LIKE ?1 || ':%'
ORDER BY ts, id
`

// Subtree records: exact match OR children (task LIKE id||':%')
func (q *Queries) ListRecordsByPrefix(ctx context.Context, taskID string) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByPrefix, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Ts,
			&i.Source,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByTask = `-- name: ListRecordsByTask :many
SELECT id, task, ts, source, text FROM record WHERE task = ? ORDER BY ts, id
`

// Exact match only
func (q *Queries) ListRecordsByTask(ctx context.Context, task string) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByTask, task)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Ts,
			&i.Source,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
