// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const clearTaskStatus = `-- name: ClearTaskStatus :exec
UPDATE task SET status = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearTaskStatus(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearTaskStatus, id)
	return err
}

const countChildren = `-- name: CountChildren :one
SELECT COUNT(*) FROM task WHERE parent_id = ?
`

func (q *Queries) CountChildren(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTasksByParent = `-- name: DeleteTasksByParent :exec
DELETE FROM task WHERE parent_id = ?
`

func (q *Queries) DeleteTasksByParent(ctx context.Context, parentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByParent, parentID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, parent_id, title, body, context, status, position, created_at, updated_at FROM task WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Context,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskContext = `-- name: GetTaskContext :one
SELECT context FROM task WHERE id = ?
`

func (q *Queries) GetTaskContext(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTaskContext, id)
	var context sql.NullString
	err := row.Scan(&context)
	return context, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO task (id, parent_id, title, body, context, status, position)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	ID       string         `db:"id"`
	ParentID sql.NullString `db:"parent_id"`
	Title    sql.NullString `db:"title"`
	Body     sql.NullString `db:"body"`
	Context  sql.NullString `db:"context"`
	Status   sql.NullString `db:"status"`
	Position sql.NullInt64  `db:"position"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.ParentID,
		arg.Title,
		arg.Body,
		arg.Context,
		arg.Status,
		arg.Position,
	)
	return err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, parent_id, title, body, context, status, position, created_at, updated_at FROM task ORDER BY position, created_at
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Context,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTasksByParent = `-- name: ListAllTasksByParent :many
SELECT id, parent_id, title, body, context, status, position, created_at, updated_at FROM task WHERE parent_id = ? ORDER BY position, created_at
`

func (q *Queries) ListAllTasksByParent(ctx context.Context, parentID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasksByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Context,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, parent_id, title, body, context, status, position, created_at, updated_at FROM task
WHERE status IS NULL OR status NOT IN ('done', 'abandoned')
ORDER BY position, created_at
`

// All tasks that are branches (status IS NULL) or non-terminal leaves
func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Context,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByParent = `-- name: ListTasksByParent :many
SELECT id, parent_id, title, body, context, status, position, created_at, updated_at FROM task
WHERE parent_id = ?
  AND (status IS NULL OR status NOT IN ('done', 'abandoned'))
ORDER BY position, created_at
`

// Immediate children excluding terminal leaves
func (q *Queries) ListTasksByParent(ctx context.Context, parentID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Context,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxChildPosition = `-- name: MaxChildPosition :one
SELECT COALESCE(MAX(position), 0) FROM task WHERE parent_id = ?
`

func (q *Queries) MaxChildPosition(ctx context.Context, parentID sql.NullString) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxChildPosition, parentID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateTaskBody = `-- name: UpdateTaskBody :exec
UPDATE task SET body = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTaskBodyParams struct {
	Body sql.NullString `db:"body"`
	ID   string         `db:"id"`
}

func (q *Queries) UpdateTaskBody(ctx context.Context, arg UpdateTaskBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskBody, arg.Body, arg.ID)
	return err
}

const updateTaskContext = `-- name: UpdateTaskContext :exec
UPDATE task SET context = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTaskContextParams struct {
	Context sql.NullString `db:"context"`
	ID      string         `db:"id"`
}

func (q *Queries) UpdateTaskContext(ctx context.Context, arg UpdateTaskContextParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskContext, arg.Context, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status sql.NullString `db:"status"`
	ID     string         `db:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}

const updateTaskTitle = `-- name: UpdateTaskTitle :exec
UPDATE task SET title = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTaskTitleParams struct {
	Title sql.NullString `db:"title"`
	ID    string         `db:"id"`
}

func (q *Queries) UpdateTaskTitle(ctx context.Context, arg UpdateTaskTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskTitle, arg.Title, arg.ID)
	return err
}
